# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import rpc_make_img_pb2 as rpc__make__img__pb2


class ShotifypyStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HtmlSnapshot = channel.unary_unary(
                '/pb.Shotifypy/HtmlSnapshot',
                request_serializer=rpc__make__img__pb2.MakeImageFromHtmlRequest.SerializeToString,
                response_deserializer=rpc__make__img__pb2.MakeImageFromHtmlResponse.FromString,
                )


class ShotifypyServicer(object):
    """Missing associated documentation comment in .proto file."""

    def HtmlSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShotifypyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HtmlSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.HtmlSnapshot,
                    request_deserializer=rpc__make__img__pb2.MakeImageFromHtmlRequest.FromString,
                    response_serializer=rpc__make__img__pb2.MakeImageFromHtmlResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.Shotifypy', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Shotifypy(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def HtmlSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.Shotifypy/HtmlSnapshot',
            rpc__make__img__pb2.MakeImageFromHtmlRequest.SerializeToString,
            rpc__make__img__pb2.MakeImageFromHtmlResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
