# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service_shotifypy.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import rpc_make_img_pb2 as rpc__make__img__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17service_shotifypy.proto\x12\x02pb\x1a\x12rpc_make_img.proto2Z\n\tShotifypy\x12M\n\x0cHtmlSnapshot\x12\x1c.pb.MakeImageFromHtmlRequest\x1a\x1d.pb.MakeImageFromHtmlResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_shotifypy_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SHOTIFYPY._serialized_start=51
  _SHOTIFYPY._serialized_end=141
# @@protoc_insertion_point(module_scope)
